name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: update repositories
      run: apt update -y
    - name: Install dependencies
      run: apt install libsfml-dev libcsfml-dev cargo rustc wget  -y
    - name: Download Font
      run: wget https://github.com/mrtuxa/hack-ttf/raw/main/Hack-Regular.ttf -o Font.ttf
    - name: Build Game
      run: cargo build --release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/mr_binaer
        asset_name: mr_binaer
        tag: ${{ github.ref }}
        overwrite: true
        body: "MrBinaer"
